# Generated by Django 4.2.24 on 2025-10-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0004_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.CharField(max_length=500),
        ),
    ]
