# Generated by Django 4.2.23 on 2025-09-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image_url',
            field=models.URLField(default='event_images/default.png', null=True),
        ),
    ]
