# Generated by Django 4.2.23 on 2025-09-19 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='image_url',
        ),
    ]
