# Generated by Django 4.2.23 on 2025-09-20 18:33

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_events_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='registration_timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='ticket_number',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.CharField(choices=[('WEB', 'Web Development'), ('CYBERSEC', 'Cyber Security'), ('ANDROID', 'Android Development'), ('AI', 'Artificial Intelligence'), ('BLOCKCHAIN', 'Blockchain'), ('IoT', 'Internate of Things'), ('CLOUD', 'Cloud Community')], db_index=True, default='Web Development', max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='events',
            index=models.Index(fields=['category', 'date'], name='events_even_categor_ed79fa_idx'),
        ),
        migrations.AddIndex(
            model_name='events',
            index=models.Index(fields=['date', 'location'], name='events_even_date_25e76d_idx'),
        ),
        migrations.AddIndex(
            model_name='events',
            index=models.Index(fields=['-date'], name='events_even_date_3ec9f1_idx'),
        ),
    ]
