# Generated by Django 4.2.24 on 2025-10-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventregistration_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.CharField(choices=[('WEB', 'Web Development'), ('CYBERSECURITY', 'Cyber Security'), ('ANDROID', 'Android Development'), ('AI', 'Artificial Intelligence'), ('BLOCKCHAIN', 'Blockchain'), ('IoT', 'Internate of Things'), ('CLOUD', 'Cloud Community')], db_index=True, default='Web Development', max_length=50),
        ),
    ]
