# Generated by Django 5.1.3 on 2025-08-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityprofile',
            name='social_media',
            field=models.ManyToManyField(related_name='social_media_communities_from_communities_app', to='communities.social_media'),
        ),
    ]
