version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: must_club_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kundan1234
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=ves2kmb$$2tiye0ai7l%tt_(0ycg8q-!_%j&%nw^=)mu%ag=14
      - DJANGO_DEBUG=True
      - DATABASE_URL=postgres://postgres:Kundan1234@db:5432/must_club_db
      - DB_NAME=must_club_db
      - DB_USER=postgres
      - DB_PASSWORD=Kundan1234
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
