# Generated by Django 5.2 on 2025-05-11 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation_WebApp', '0004_eventregistration_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='registration_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.CharField(choices=[('WEB', 'Web Development'), ('CYBERSEC', 'Cyber Security'), ('ANDROID', 'Android Development'), ('AI', 'Artificial Intelligence'), ('BLOCKCHAIN', 'Blockchain'), ('IoT', 'Internate of Things'), ('CLOUD', 'Cloud Computing')], default='Web Development', max_length=50),
        ),
    ]
