# Generated by Django 5.2 on 2025-05-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation_WebApp', '0005_events_registration_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='registration_link',
        ),
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.CharField(choices=[('WEB', 'Web Development'), ('CYBERSEC', 'Cyber Security'), ('ANDROID', 'Android Development'), ('AI', 'Artificial Intelligence'), ('BLOCKCHAIN', 'Blockchain'), ('IoT', 'Internate of Things')], default='Web Development', max_length=50),
        ),
    ]
