# Generated by Django 5.1.3 on 2025-08-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation_WebApp', '0006_remove_events_registration_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.CharField(choices=[('WEB', 'Web Development'), ('CYBERSEC', 'Cyber Security'), ('ANDROID', 'Android Development'), ('AI', 'Artificial Intelligence'), ('BLOCKCHAIN', 'Blockchain'), ('IoT', 'Internate of Things'), ('CLOUD', 'Cloud Community')], default='Web Development', max_length=50),
        ),
    ]
