# Generated by Django 5.1.3 on 2025-08-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation_WebApp', '0008_alter_eventregistration_unique_together_and_more'),
        ('comments', '0002_alter_comment_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='EventRegistration',
        ),
    ]
