# Generated by Django 5.1.3 on 2025-08-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0004_alter_executivemember_community'),
        ('Innovation_WebApp', '0009_delete_events_delete_eventregistration'),
        ('communities', '0002_alter_communityprofile_social_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Community',
        ),
        migrations.RemoveField(
            model_name='communityprofile',
            name='club',
        ),
        migrations.RemoveField(
            model_name='communityprofile',
            name='co_lead',
        ),
        migrations.RemoveField(
            model_name='communityprofile',
            name='community_lead',
        ),
        migrations.RemoveField(
            model_name='communityprofile',
            name='secretary',
        ),
        migrations.RemoveField(
            model_name='communityprofile',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='communitysession',
            name='community',
        ),
        migrations.DeleteModel(
            name='CommunityMember',
        ),
        migrations.DeleteModel(
            name='Social_media',
        ),
        migrations.DeleteModel(
            name='CommunityProfile',
        ),
        migrations.DeleteModel(
            name='CommunitySession',
        ),
    ]
