# Generated by Django 5.1.3 on 2025-08-19 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about_us', models.TextField()),
                ('vision', models.CharField(max_length=500)),
                ('mission', models.CharField(max_length=500)),
                ('social_media', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutiveMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('LEAD', 'Community Lead'), ('CO_LEAD', 'Co-Lead'), ('SECRETARY', 'Secretary')], max_length=10)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
