# Generated by Django 5.1.3 on 2025-08-18 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0003_alter_executivemember_unique_together'),
        ('communities', '0002_alter_communityprofile_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executivemember',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_members', to='communities.communityprofile'),
        ),
    ]
